KK.WebClient/Models/EnquiryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace KK.WebClient.Models
{
    /// <summary>
    /// Note : This View Model is used by API and Controller.
    /// Data Contract and Data Member is used by API
    /// </summary>
    [DataContract]
    public class EnquiryViewModel
    {
        [Required]
        [DataMember(IsRequired = true)]
        [Display(Name = "Car Ads ID")]
        public Guid CarAdsId { get; set; }

        [Required]
        [DataMember(IsRequired = true)]
        [Display(Name = "Full name")]
        public string Name { get; set; }

        
        [Required]
        [DataMember(IsRequired = true)]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
    }
}

KK.WebClient/Areas/OldCar/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KK.Domain.Models;
using KK.Domain.Services.Interfaces;

namespace KK.WebClient.Areas.oldCar.Controllers
{
    public class AdsController : Controller
    {
        
        private readonly ICarAdsService _carAdsService;

        public AdsController(ICarAdsService carAdsService)
        {
            _carAdsService = carAdsService;
        }

        // GET: /oldCar/ads/
        public ActionResult Index()
        {
            return View(_carAdsService.GetAll());
        }

        // GET: /oldCar/ads/detail/{id}
        public ActionResult Detail(Guid id)
        {
            var detail = _carAdsService.GetById(id);
            return View(detail);
        }

    }
}

KK.WebClient/Areas/OldCar/Controllers/EnquiriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KK.Domain.Models;
using KK.Domain.Services.Interfaces;
using KK.WebClient.Models;

namespace KK.WebClient.Areas.oldCar.Controllers
{
    public class EnquiriesController : Controller
    {        
        private readonly ICarAdsService _carAdsService;
        private readonly IEnquiryService _enquiryService;

        public EnquiriesController(ICarAdsService carAdsService, IEnquiryService enquiryService)
        {
            _carAdsService = carAdsService;
            _enquiryService = enquiryService;
        }

        // GET: /oldCar/enquiries
        public ActionResult Index()
        {
            return View(_enquiryService.GetAll());
        }


        // POST: /oldCar/enquiries/add
        [HttpPost]        
        [ValidateAntiForgeryToken]
        public ActionResult AddEnquiry(EnquiryViewModel enquiryViewModel)
        {
            var enquiry = new Enquiry
                          {
                              CarAds = _carAdsService.GetById(enquiryViewModel.CarAdsId),
                              EmailAddress = enquiryViewModel.EmailAddress, 
                              Name = enquiryViewModel.Name
                          };

            _enquiryService.AddEnquiry(enquiry);
            return View(enquiry);
        }
    }
}

KK.WebClient/Areas/OldCar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KK.WebClient.Areas.oldCar.Controllers
{
    public class HomeController : Controller
    {
        // GET: /oldCar/Home/
        public ActionResult Index()
        {
            return View();
        }



    }
}

KK.WebClient/Controllers/Apis/CarAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using KK.Domain.Models;
using KK.Domain.Services.Interfaces;

namespace KK.WebClient.Controllers.Apis
{
    /// <summary>
    /// API controller to Car Ads
    /// </summary>
    public class CarAdsController : ApiController
    {
        private readonly ICarAdsService _carAdsService;

        public CarAdsController(ICarAdsService carAdsService)
        {
            _carAdsService = carAdsService;
        }

        // GET: /api/carAds
        public IEnumerable<CarAds> Get()
        {
            return _carAdsService.GetAll();
        }

        // GET: /api/carAds/{id}
        public CarAds Get(Guid id)
        {
            return _carAdsService.GetById(id);
        }

    }
}

KK.WebClient/Controllers/Apis/EnquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using KK.Domain.Models;
using KK.Domain.Services.Interfaces;
using KK.WebClient.Models;

namespace KK.WebClient.Controllers.Apis
{
    /// <summary>
    /// API controller to Enquiry
    /// </summary>    
    public class EnquiryController : ApiController
    {
        private readonly IEnquiryService _enquiryService;
        private readonly ICarAdsService _carAdsService;

        public EnquiryController(IEnquiryService enquiryService, ICarAdsService carAdsService)
        {
            _enquiryService = enquiryService;
            _carAdsService = carAdsService;
        }

        // GET: /api/enquiry
        public IEnumerable<Enquiry> Get()
        {
            return _enquiryService.GetAll();
        }

        // POST: /api/enquiry
        public Guid Post(EnquiryViewModel enquiryViewModel)
        {
            var enquiry = new Enquiry
            {
                CarAds = _carAdsService.GetById(enquiryViewModel.CarAdsId),
                EmailAddress = enquiryViewModel.EmailAddress,
                Name = enquiryViewModel.Name
            };

            return _enquiryService.AddEnquiry(enquiry);
        }
    }
}

KK.WebClient/Controllers/CarAppController.cs
using System;
using System.Web.Mvc;

namespace KK.WebClient.Controllers
{
    /// <summary>
    /// This is SPA (Single Page App) controller
    /// </summary>    
    public class CarAppController : Controller
    {
        // GET: /carApp/Home/
        public ActionResult Index()
        {
            return View();
        }
    }
}

KK.WebClient/Areas/OldCar/Views/Ads/Detail.cshtml
@using KK.Domain.Models
@using KK.WebClient.Models
@model CarAds

@{
    ViewBag.Title = "Car Ads Detail";    
}

@if (Model != null)
{
    <h2>Car Ads Detail</h2>
    Html.RenderPartial("_CarAdsDetail", Model);
    Html.RenderPartial("_EnquiryForm", new EnquiryViewModel {CarAdsId = Model.Id});
}
else
{
    <h2>Unable to find Car ads.</h2>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KK.WebClient/Areas/OldCar/Views/Ads/Index.cshtml
@model List<KK.Domain.Models.CarAds>

@{
    ViewBag.Title = "Car Ads";    
}


<h2>Car Listing</h2>
<ul class="uilist-none grid__cell grid__cell--center margin-an padding-an">
    @foreach (var carAds in Model)
    {      
        Html.RenderPartial("_CarAdsDetail", carAds);      
    }
    
</ul>

KK.WebClient/Areas/OldCar/Views/Enquiries/AddEnquiry.cshtml
@using KK.Domain.Models
@model Enquiry

<h2>Thanks for enquiry for this car</h2>
<h3>Name : @Model.Name</h3>
<h3>Email Address : @Model.EmailAddress</h3>
@{
    if (Model.CarAds != null)
    {
        Html.RenderPartial("_CarAdsDetail", Model.CarAds);    
    }    
}

KK.WebClient/Areas/OldCar/Views/Enquiries/Index.cshtml
@model List<KK.Domain.Models.Enquiry>

@foreach (var enquiry in Model)
{
    <h3>Name : @enquiry.Name</h3>
    <h3>Email : @enquiry.EmailAddress</h3>

    if (enquiry.CarAds != null)
    {
        Html.RenderPartial("_CarAdsDetail", enquiry.CarAds);   
    }
    
    <hr/>    
}

KK.WebClient/Areas/OldCar/Views/Home/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";    
}

<div class="hero-unit">
    <h1>KK MVC demo - server side render style</h1>
    <p>Please select Tab above for cars and enquiries</p>

    <div>
        <h2> Technology used :</h2>
        <ul>
            <li>.Net 4.5</li>
            <li>C# + MVC 4</li> 
            <li>Razor Template</li>            
            <li>Autofac for IOC Container</li>
            <li>Elmah for Error Logging</li>
            <li>NUnit for Unit test</li>
            <li>Moq for Mocking framework</li>
            <li>Twitter Bootstrap for CSS style guide</li>
            <li>Nuget for Package Manager</li>
            <li>SOLID Principle</li>           
        </ul>
    </div>
    
    For SPA Demo, please check it <a href="/">HERE.</a>
</div>

KK.WebClient/Areas/OldCar/Views/Shared/_CarAdsDetail.cshtml
@using KK.Domain.Models
@model CarAds

<ul class="uilist-none grid__cell grid__cell--center margin-an padding-an">
        <li class="result result--listings nbfc margin-bm padding-ll padding-rmm">
        <div class="relative highlight-none">                
            <a href="/oldCar/ads/detail/@Model.Id" class="result--listings__listing result--listings__listing--a link-block">
                <h1 class="result__title--new text-break text-normal margin-bn">@Model.CarListed.Make @Model.CarListed.Model @Model.CarListed.Year</h1>
                <h2 class="result__sub-title--new result__sub-title--highlight margin-an">
                    @{
                        Html.RenderPartial("_CarPriceTag", Model.CarListed);
                    }
                </h2>
                <h2 class="result__sub-title--new result__sub-title--highlight margin-an">@Model.ListedDate.ToShortDateString()</h2>
                <p>@Model.Comments</p>                    
                <h5>Contact email address : @Model.ContactDetail.EmailAddress</h5>
                @{
                    Html.RenderPartial("_SellerDetail", Model.ContactDetail);
                }                
            </a>                
        </div>
    </li>    
</ul>

KK.WebClient/Areas/OldCar/Views/Shared/_CarPriceTag.cshtml
@using KK.Domain.Models
@model Car

@if (Model.PriceType == CarPriceType.POA)
{
    @Html.Raw("POA");
}
else
{
    @Html.Raw(String.Format("{0:C} {1}", Model.Price, Model.PriceType));
}

KK.WebClient/Areas/OldCar/Views/Shared/_DealerSellerDetail.cshtml
@using KK.Domain.Models
@model DealerSellerDetail

<h5>Dealer ABN : @Model.DealerABN</h5>

KK.WebClient/Areas/OldCar/Views/Shared/_EnquiryForm.cshtml
@model KK.WebClient.Models.EnquiryViewModel

<div>
    <h2>Enquire Online</h2>
    @using (Html.BeginForm("AddEnquiry","Enquiries"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <fieldset>
            <legend>Enquiry Form</legend>            
            @Html.HiddenFor(m=>m.CarAdsId, Model.CarAdsId)
            <ol>
                <li>
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name)
                </li>
                <li>
                    @Html.LabelFor(m => m.EmailAddress)
                    @Html.TextBoxFor(m => m.EmailAddress)
                </li>                
            </ol>
            <input type="submit" value="Send" />
        </fieldset>	
    }
    
</div>    

KK.WebClient/Areas/OldCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <title>KK - MVC4 Demo</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body data-ng-app="main" data-ng-controller="RootController">
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href='/oldCar'>KK-MVC Demo</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li data-ng-class="{active : activeViewPath==='/oldCar'}"><a href='/oldCar'>Home</a></li>
                        <li data-ng-class="{active : activeViewPath==='/oldCar/ads'}"><a href="/oldCar/ads">Car Listing</a></li>
                        <li data-ng-class="{active : activeViewPath==='/oldCar/enquiries'}"><a href='/oldCar/enquiries'>Enquiries</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

KK.WebClient/Areas/OldCar/Views/Shared/_PrivateSellerDetail.cshtml
@using KK.Domain.Models
@model PrivateSellerDetail
<h5>Contact Name : @Model.ContactName</h5>
<h5>Phone : @Model.Phone</h5>

KK.WebClient/Areas/OldCar/Views/Shared/_SellerDetail.cshtml
@using KK.Domain.Models
@model SellerDetail

@if (Model is PrivateSellerDetail)
{
    Html.RenderPartial("_PrivateSellerDetail", Model as PrivateSellerDetail);
}
else{
    Html.RenderPartial("_DealerSellerDetail", Model as DealerSellerDetail);
}

KK.WebClient/Views/CarApp/Index.cshtml
<!--This is where the main views would get loaded for SPA
    This page is the container page for all sub views that get loaded.
    The sub views that would get loaded into ng-view would not inherit the master page, 
    and hence would only send relevant html fargments to render specific views.-->
<div data-ng-view=""></div>

KK.WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <title>KK - MVC4 Demo</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body data-ng-app="main" data-ng-controller="RootController">
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href='/'>KK-MVC4 Demo</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li data-ng-class="{active : activeViewPath==='/'}"><a href='/'>Home</a></li>
                        <li data-ng-class="{active : activeViewPath==='/car/ads'}"><a href="/car/ads">Car Listing</a></li>
                        <li data-ng-class="{active : activeViewPath==='/car/enquiries'}"><a href='/car/enquiries'>Enquiries</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/carApp")
    @RenderSection("scripts", required: false)
</body>
</html>